### ISSUE TITLE
Static files

### ISSUE THREAD

**Issue by chinthuhashtag** [pogasanov/django-docker-aws#1]
How can i use static folder. to store images and css?

**Comment by pogasanov** [comment]
You'll need to do following:
* Configure django to store all static files to specific folder, for example /srv/static. Think that's `STATIC_ROOT` option.
* Modify startup script to run `python manage.py collectstatic` so django will update static files when container starts
* In `docker-compose.yml` you have to make common volume for `app` and `nginx` container so nginx can access those files
* In nginx configs you'll need to allow direct access for static files with the same url, as in django. By default that's `/static/`
* You'll need to update AWS nginx server to access those files as well.

I'll update repo as soon as I get working AWS account.

**Comment by pogasanov** [comment]
Added [part 2](https://pogasanov.ru/posts/django-docker-aws-2) that describe serving static files and several other issues.

New repository version should serve static files out-of-the-box.
